<?php

declare(strict_types=1);

/*
 * This file is part of Twifty Virtual Filesystem.
 *
 * (c) Owen Parry <waldermort@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Twifty\VirtualFileSystem\Test\Inject;

use PHPUnit\Framework\TestCase;
use Twifty\VirtualFileSystem\Inject\RealPath;

/**
 * Test case for RealPath.
 *
 * Generated by twifty-test-generator 0.0.1-beta.1 on 2017-07-18.
 *
 * @author Owen Parry <waldermort@gmail.com>
 */
class RealPathTest extends TestCase
{
    public function testRealPath()
    {
        $vfs = new \Twifty\VirtualFileSystem\VirtualFileSystem([
            'foo' => [
                'bar' => [
                    'baz' => '',
                ],
            ],
        ]);
        $vfs->createSymlink('/foo/link', '/foo');

        $proxy = new RealPath($vfs->path('/'));

        $this->assertSame('realpath', $proxy->getName());

        $result = ($proxy)('/foo/link/bar/baz/./');

        $this->assertSame($vfs->path('/foo/bar/baz'), $result);
        $this->assertFalse($proxy('/foo/missing/link'));
    }

    public function testCallGlobal()
    {
        $path = __DIR__.'/../Inject/./';
        
        $this->assertSame(\realpath($path), (new RealPath())($path));
    }
}
